/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krypton.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterAll;

public class EmailAvailableTest {
	static KryptonClient client = new KryptonClient("https://nusid.net/krypton-auth");
	static String email = "emailavailable@example.com";
	static String password = "ex@mplePassword123";

	@Test
	public void testEmailAvailable() throws Exception {

		boolean isAvailable = client.isEmailAvailable(email).get();
		assertTrue(isAvailable);
		client.register(email, password).get();
		isAvailable = client.isEmailAvailable(email).get();
		assertFalse(isAvailable);

	}

	@AfterAll
	public static void cleanUp() {
		try {
			client.login(email, password).get();
			client.delete(password).get();
		} catch (Exception e) {
			System.out.println(e);
		}

	}

}
