/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krypton.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class KryptonClientTest {
    @Test
    public void test1() {
        KryptonClient client = new KryptonClient("http://localhost:5000/auth");
        try {
            client.register("toto@toto.com", "totototo");
        } catch (Exception e) {
            fail("Cannot register");
        }
        try {
            client.login("toto@toto.com", "totototo");
        } catch (Exception e) {
            fail("Cannot register");
        }
    }
}