/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krypton.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterAll;

public class RegisterTest {
	static KryptonClient client = new KryptonClient("https://nusid.net/krypton-auth");
	static String email = "register.test@example.com";
	static String password = "ex@mplePassword123";

	@Test
	public void testRegister() {

		try {
			boolean isRegistered = client.register(email, password);
			assertTrue(isRegistered);
		} catch (Exception e) {
			System.out.println(e);
			fail(e);
		}
	}

	@AfterAll
	public static void cleanUp() {
		try {
			client.login(email, password);
			client.delete(password);
		} catch (Exception e) {
			System.out.println(e);
		}

	}
}